// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvavUn08Rv6R_edXD7Yj-caytFhWY6c8Y',
    appId: '1:85586840117:web:759237a65f9c5376eb7f7c',
    messagingSenderId: '85586840117',
    projectId: 'prolific-f8b25',
    authDomain: 'prolific-f8b25.firebaseapp.com',
    storageBucket: 'prolific-f8b25.appspot.com',
    measurementId: 'G-74ZV49WWSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeyogeIi9hjvo46IvAGtdJKM47yGaYE3Y',
    appId: '1:85586840117:android:5b3bf9c8d22ab065eb7f7c',
    messagingSenderId: '85586840117',
    projectId: 'prolific-f8b25',
    storageBucket: 'prolific-f8b25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlwb1AnRMftr08OHUn36T_OU01mGRosJI',
    appId: '1:85586840117:ios:2ef8499736c75952eb7f7c',
    messagingSenderId: '85586840117',
    projectId: 'prolific-f8b25',
    storageBucket: 'prolific-f8b25.appspot.com',
    iosClientId: '85586840117-hvmn5rcsuahuic0op2v7004b4k00n2dh.apps.googleusercontent.com',
    iosBundleId: 'com.example.prolific',
  );
}
